server:
  port: 8082
  servlet:
    context-path: /payproc

spring:
  application:
    name: pay-proc
  
  datasource:
    url: jdbc:postgresql://postgres:5432/payDemo
    username: payadmin
    password: PayStr0ng!2024
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    user:
      name: payproc
      password: ${PROC_PASSWORD:ProcPass123!}

services:
  pay-secure:
    url: http://pay-secure:8081/paysecure
    username: admin
    password: ${PAY_SECURE_PASSWORD:SecurePass123!}
  
  pay-bridge:
    url: http://pay-bridge:8083/paybridge
    username: paybridge
    password: ${PAY_BRIDGE_PASSWORD:BridgePass123!}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.payment.payproc: DEBUG