server:
  port: 8083
  servlet:
    context-path: /paybridge

spring:
  application:
    name: pay-bridge
  security:
    user:
      name: paybridge
      password: ${BRIDGE_PASSWORD:BridgePass123!}

logging:
  level:
    root: INFO
    com.payment.paybridge: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"